---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: cells
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: CELLS_WORKING_DIR
            value: /etc/config
        command: [ "./cells", "start", "-t broker", "--registry_address", "nats:4222" ]
        volumeMounts:
          - mountPath: /etc/config
            name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: config