files:
  - source: '*/lang/box/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar: ar
        de: de
        es-ES: es-es
        fr: fr
        fr-CA: fr-ca
        it: it
        ja: ja
        ko: ko
        lv: lv
        nl: nl
        pt-BR: pt-br
        pt-PT: pt-pt
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: '*/i18n/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar: ar
        de: de
        es-ES: es-es
        fr: fr
        fr-CA: fr-ca
        it: it
        ja: ja
        ko: ko
        lv: lv
        nl: nl
        pt-BR: pt-br
        pt-PT: pt-pt
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: '*/i18n/*/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar: ar
        de: de
        es-ES: es-es
        fr: fr
        fr-CA: fr-ca
        it: it
        ja: ja
        ko: ko
        lv: lv
        nl: nl
        pt-BR: pt-br
        pt-PT: pt-pt
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: '*/i18n/*/conf/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar: ar
        de: de
        es-ES: es-es
        fr: fr
        fr-CA: fr-ca
        it: it
        ja: ja
        ko: ko
        lv: lv
        nl: nl
        pt-BR: pt-br
        pt-PT: pt-pt
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
