apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cells-chart.fullname" . }}
data:
  source: |
    export VAULT_TOKEN=$(cat /vault/secrets/token)
  install-conf.yaml: |
    proxyconfigs:
      - binds:
          - 0.0.0.0:8080
        tlsconfig:
          selfsigned:

    dbconnectiontype: tcp
    dbtcphostname: {{ include "cells-chart.mariadbHost" . }}
    dbtcpport: {{ include "cells-chart.mariadbPort" . }}
    dbtcpname: cells
    dbtcpuser: root
    dbtcppassword: {$MARIADB_ROOT_PASSWORD}

    documentsdsn: {{ include "cells-chart.mongodbURL" . }}/cells
    usedocumentsdsn: true

    # Defined in .env file
    frontendlogin: admin
    frontendpassword: P@ssw0rd

    dstype: S3
    dss3custom: {{ include "cells-chart.minioURL" . }}
    dss3apikey: {$MINIO_ROOT_USER}
    dss3apisecret: {$MINIO_ROOT_PASSWORD}
    dss3bucketdefault: pydiods1
    dss3bucketpersonal: personal
    dss3bucketcells: cellsdata
    dss3bucketbinaries: binaries
    dss3bucketthumbs: thumbnails
    dss3bucketversions: versions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cells-vault
data:
  bootstrap.sh: |
    #!/bin/sh

    OUTPUT=/tmp/output.txt
    export VAULT_TOKEN=$(cat /root/.vault-token)
    export VAULT_ADDR=http://127.0.0.1:8200

    vault operator init -n 1 -t 1 >> ${OUTPUT?}

    unseal=$(cat ${OUTPUT?} | grep "Unseal Key 1:" | sed -e "s/Unseal Key 1: //g")
    root=$(cat ${OUTPUT?} | grep "Initial Root Token:" | sed -e "s/Initial Root Token: //g")

    vault operator unseal ${unseal?}

    vault login -no-print ${root?}

    vault secrets enable -version=2 -path=secret kv
    vault secrets enable -version=2 -path=caddycerts kv

    vault auth enable kubernetes

    vault write auth/kubernetes/config \
        kubernetes_host=https://kubernetes.default.svc \
        kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

    vault policy write app /vault/userconfig/cells-vault/app-policy.hcl

    vault write auth/kubernetes/role/app \
       bound_service_account_names=app \
       bound_service_account_namespaces=cells \
       policies=app \
       ttl=24h

    vault token create -policy=app

  app-policy.hcl: |
    path "auth/token/lookup-self" {
        capabilities = ["read"]
    }
    path "sys/internal/ui/mounts/auth/token/lookup-self" {
        capabilities = ["read"]
    }
    path "secret/*" {
        capabilities = ["create", "update", "read", "delete"]
    }
    path "caddycerts/*" {
        capabilities = ["create", "update", "read", "delete"]
    }
